import base64
import io
import os
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable, Image as RLImage, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)
from pypdf import PdfReader, PdfWriter

PURPLE = colors.HexColor("#4B1C82")
LIGHT_PURPLE = colors.HexColor("#F3E8FF")
LIGHT_GRAY = colors.HexColor("#F9FAFB")
BORDER_GRAY = colors.HexColor("#E5E7EB")
TEXT_GRAY = colors.HexColor("#6B7280")
GREEN = colors.HexColor("#16A34A")


def _styles():
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle("H1", parent=base["Heading1"], fontSize=18, textColor=PURPLE, spaceAfter=4),
        "h2": ParagraphStyle("H2", parent=base["Heading2"], fontSize=12, textColor=PURPLE, spaceAfter=4),
        "body": ParagraphStyle("Body", parent=base["Normal"], fontSize=10, leading=14, spaceAfter=3),
        "small": ParagraphStyle("Small", parent=base["Normal"], fontSize=8, textColor=TEXT_GRAY),
        "center": ParagraphStyle("Center", parent=base["Normal"], fontSize=9, alignment=TA_CENTER, textColor=TEXT_GRAY),
    }


def generate_signed_form_pdf(req, pdf_dir: str) -> bytes:
    """
    Build a PDF record of a signed consent form.
    If the form template has an attached PDF, it is appended after the record page.
    Returns the combined PDF as bytes.
    """
    s = _styles()
    scout = req.scout
    guardian = req.guardian
    form = req.form_template

    signed_at_str = (
        req.signed_at.strftime("%d %B %Y at %H:%M UTC") if req.signed_at else "—"
    )
    generated_at = datetime.now(timezone.utc).strftime("%d %B %Y at %H:%M UTC")

    # ── Build record page with reportlab ──────────────────────────────────────

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )

    story = []

    # Header
    story.append(Paragraph("Scout Group — Consent Form Record", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=2, color=PURPLE, spaceAfter=8))
    story.append(Spacer(1, 0.3 * cm))

    # Form name + description
    story.append(Paragraph(form.name, s["h2"]))
    if form.description:
        story.append(Paragraph(form.description, s["body"]))
    story.append(Spacer(1, 0.4 * cm))

    # Details table
    rows = [
        ["Scout", f"{scout.first_name} {scout.last_name}"],
        ["Guardian / Parent", f"{guardian.first_name} {guardian.last_name}"],
        ["Relationship", guardian.relationship_to_scout or "—"],
        ["Email", guardian.email],
        ["Phone", guardian.phone or "—"],
        ["Date Signed", signed_at_str],
        ["Signed By", req.signed_by_name or f"{guardian.first_name} {guardian.last_name}"],
        ["Status", "SIGNED"],
    ]
    tbl = Table(rows, colWidths=[4.5 * cm, 12 * cm])
    tbl.setStyle(TableStyle([
        ("FONTNAME",       (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",       (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",       (0, 0), (-1, -1), 10),
        ("BACKGROUND",     (0, 0), (0, -1), LIGHT_PURPLE),
        ("ROWBACKGROUNDS", (1, 0), (1, -1), [colors.white, LIGHT_GRAY]),
        ("GRID",           (0, 0), (-1, -1), 0.5, BORDER_GRAY),
        ("PADDING",        (0, 0), (-1, -1), 6),
        ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
        # Green bold for the SIGNED status cell
        ("TEXTCOLOR",      (1, -1), (1, -1), GREEN),
        ("FONTNAME",       (1, -1), (1, -1), "Helvetica-Bold"),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 0.6 * cm))

    # Signature
    story.append(Paragraph("Signature", s["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_GRAY, spaceAfter=6))

    if req.signature_data:
        raw = req.signature_data
        if raw.startswith("data:"):
            raw = raw.split(",", 1)[1]
        sig_bytes = base64.b64decode(raw)
        sig_buf = io.BytesIO(sig_bytes)
        story.append(RLImage(sig_buf, width=9 * cm, height=3.5 * cm))
        story.append(Spacer(1, 0.2 * cm))
        signer = req.signed_by_name or f"{guardian.first_name} {guardian.last_name}"
        story.append(Paragraph(f"Digitally signed by {signer} on {signed_at_str}", s["small"]))
    else:
        story.append(Paragraph("Signed manually — no digital signature captured.", s["body"]))

    story.append(Spacer(1, 0.8 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_GRAY, spaceAfter=4))
    story.append(Paragraph(f"Generated by ScoutGroupDocMgr on {generated_at}.", s["center"]))

    doc.build(story)
    buf.seek(0)
    record_bytes = buf.read()

    # ── Merge with form template PDF if one is attached ───────────────────────

    if form.pdf_filename:
        form_pdf_path = os.path.join(pdf_dir, form.pdf_filename)
        if os.path.exists(form_pdf_path):
            writer = PdfWriter()
            for page in PdfReader(io.BytesIO(record_bytes)).pages:
                writer.add_page(page)
            for page in PdfReader(form_pdf_path).pages:
                writer.add_page(page)
            out = io.BytesIO()
            writer.write(out)
            out.seek(0)
            return out.read()

    return record_bytes
